open Core_kernel
open Middle
open! Lower_expr
open! Lower_stmt
open Lower_functions
open Cpp

let standalone_functions = ref false

let stanc_args_to_print =
  let sans_model_and_hpp_paths x =
    not
      String.(
        is_suffix ~suffix:".stan" x
        && not (is_prefix ~prefix:"--filename-in-msg" x)
        || is_prefix ~prefix:"--o" x) in
  (* Ignore the "--o" arg, the stan file and the binary name (bin/stanc). *)
  Array.to_list Sys.argv |> List.tl_exn
  |> List.filter ~f:sans_model_and_hpp_paths
  |> String.concat ~sep:" "

(** Create a variable for the name of model function.
  @param prog_name Name of the Stan program.
  @param fname Name of the function.
 *)
let gen_function__ prog_name fname =
  [ VarDef
      (make_var_defn ~static:true ~constexpr:true
         ~type_:(Const (Pointer (Type_literal "char"))) ~name:"function__"
         ~init:
           (Assignment
              (Exprs.literal_string (prog_name ^ "_namespace::" ^ fname)) )
         () ) ]
  @ Stmts.unused "function__"

let version = TopComment "Code generated by %%NAME%% %%VERSION%%"
let includes = Preprocessor (Include "stan/model/model_header.hpp")
let lower_model_private _ = []
let lower_model_public _ = []

let model_public_basics name =
  [ FunDef
      (make_fun_defn ~inline:true ~return_type:Types.string ~name:"model_name"
         ~cv_qualifiers:[Const; Final]
         ~body:[Return (Some (Exprs.literal_string name))]
         () )
  ; FunDef
      (make_fun_defn ~inline:true
         ~return_type:(Types.std_vector Types.string)
         ~name:"model_compile_info"
         ~body:
           [ Return
               (Some
                  (Exprs.std_vector_expr Types.string
                     [ Exprs.literal_string
                         "stanc_version = %%NAME%%3 %%VERSION%%"
                     ; Exprs.literal_string
                         ("stancflags = " ^ stanc_args_to_print) ] ) ) ]
         () ) ]

let lower_model ({Program.prog_name; _} as p) =
  let private_members = lower_model_private p in
  let public_members = model_public_basics prog_name @ lower_model_public p in
  Class
    (make_class_defn ~name:prog_name ~final:true
       ~base:(Type_literal ("public model_base_crtp<" ^ prog_name ^ ">"))
       ~private_members ~public_members () )

(** Create the model's namespace. *)
let namespace Program.{prog_name; _} = prog_name ^ "_namespace"

let usings =
  [ TopUsing ("stan::model::model_base_crtp", None)
  ; TopUsing ("namespace stan::math", None) ]

(** Model boilerplate. This abuses the Cpp "Literal" expression
        since we never use things like operator::new elsewhere *)
let new_model_boilerplate Program.{prog_name; _} =
  let new_model =
    let args =
      [ (Ref (Type_literal "stan::io::var_context"), "data_context")
      ; (Type_literal "unsigned int", "seed")
      ; (Pointer (Type_literal "std::ostream"), "msg_stream") ] in
    let body =
      [ VarDef
          (make_var_defn ~type_:(Pointer (Type_literal "stan_model")) ~name:"m"
             ~init:
               (Assignment
                  (Literal "new stan_model(data_context, seed, msg_stream)") )
             () ); Return (Some (Literal "*m")) ] in
    FunDef
      (make_fun_defn ~name:"new_model"
         ~return_type:(Ref (Type_literal "stan::model::model_base")) ~args ~body
         () ) in
  let profile_data =
    FunDef
      (make_fun_defn ~name:"get_stan_profile_data"
         ~return_type:(Ref (Type_literal "stan::math::profile_map"))
         ~body:[Return (Some (Literal (prog_name ^ "_namespace::profiles__")))]
         () ) in
  [ TopUsing
      ( "stan_model"
      , Some (Type_literal (prog_name ^ "_namespace::" ^ prog_name)) )
  ; Preprocessor
      (IfNDef ("USING_R", [TopComment "Boilerplate"; new_model; profile_data]))
  ]

let lower_program (p : Program.Typed.t) : Cpp.program =
  Hashtbl.clear Expression_gen.map_rect_calls ;
  (* First, do some transformations on the MIR itself before we begin printing it.*)
  let p, s = Locations.prepare_prog p in
  let model_contents =
    usings @ Locations.gen_globals s
    @ collect_functors_functions p
    @ if !standalone_functions then [] else [lower_model p] in
  let model_namespace = Namespace (namespace p, model_contents) in
  let global_fns =
    if !standalone_functions then
      List.concat_map
        ~f:(lower_standalone_fun_def (namespace p))
        p.functions_block
    else new_model_boilerplate p in
  [version; includes; model_namespace] @ global_fns
