open Core_kernel
open Core_kernel.Poly
open Middle
open! Lower_expr
open! Lower_stmt
open Lower_functions
open Cpp

let standalone_functions = ref false

let stanc_args_to_print =
  let sans_model_and_hpp_paths x =
    not
      String.(
        is_suffix ~suffix:".stan" x
        && not (is_prefix ~prefix:"--filename-in-msg" x)
        || is_prefix ~prefix:"--o" x) in
  (* Ignore the "--o" arg, the stan file and the binary name (bin/stanc). *)
  Array.to_list Sys.argv |> List.tl_exn
  |> List.filter ~f:sans_model_and_hpp_paths
  |> String.concat ~sep:" "

let get_unconstrained_param_st lst =
  match lst with
  | _, {Program.out_block= Parameters; out_unconstrained_st= st; _} -> (
    match SizedType.get_dims_io st with
    | [] -> Some [Expr.Helpers.loop_bottom]
    | ls -> Some ls )
  | _ -> None

let get_constrained_param_st lst =
  match lst with
  | _, {Program.out_block= Parameters; out_constrained_st= st; _} -> (
    match SizedType.get_dims_io st with
    | [] -> Some [Expr.Helpers.loop_bottom]
    | ls -> Some ls )
  | _ -> None

let lower_num_param (dims : Expr.Typed.t list) =
  match dims with
  | [] -> Literal "0"
  | [d] -> lower_expr d
  | d1 :: dims ->
      Parens
        (List.fold ~init:(lower_expr d1) ~f:Expression_syntax.( * )
           (lower_exprs dims) )

(** Create a variable for the name of model function.
  @param prog_name Name of the Stan program.
  @param fname Name of the function.
 *)
let gen_function__ prog_name fname =
  [ VarDef
      (make_var_defn ~static:true ~constexpr:true
         ~type_:(Const (Pointer (Type_literal "char"))) ~name:"function__"
         ~init:
           (Assignment
              (Exprs.literal_string (prog_name ^ "_namespace::" ^ fname)) )
         () ) ]
  @ Stmts.unused "function__"

let version = TopComment "Code generated by %%NAME%% %%VERSION%%"
let includes = Preprocessor (Include "stan/model/model_header.hpp")

(** Print the private members of the model class

  Accounting for types that can be moved to OpenCL.
  @param ppf A formatter
  @param vident name of the private member.
  @param ut The unsized type to print.
 *)
let lower_data_decl (vident, ut) : defn =
  let data_vident =
    match Transform_Mir.is_opencl_var vident with
    | false when UnsizedType.is_eigen_type ut -> vident ^ "_data__"
    | _ -> vident in
  TopVarDef (lower_unsized_decl data_vident ut DataOnly)

(** Create maps of Eigen types*)
let lower_map_decl (vident, ut) : defn =
  let eigen_map t ndims =
    TopVarDef
      (make_var_defn
         ~type_:(TypeTrait ("Eigen::Map", [t]))
         ~name:vident
         ~init:
           (InitalizerList
              (Literal "nullptr" :: List.init ndims ~f:(fun _ -> Literal "0"))
           )
         () ) in
  let scalar = local_scalar ut DataOnly in
  let open Types in
  match ut with
  | UMatrix -> eigen_map (matrix scalar) 2
  | URowVector -> eigen_map (row_vector scalar) 1
  | UVector -> eigen_map (vector scalar) 1
  | UComplexMatrix -> eigen_map (matrix (complex scalar)) 2
  | UComplexRowVector -> eigen_map (row_vector (complex scalar)) 1
  | UComplexVector -> eigen_map (vector (complex scalar)) 1
  | x ->
      Common.FatalError.fatal_error_msg
        [%message
          "Error during Map data construction for " vident " of type "
            (x : UnsizedType.t)]

let rec top_level_decls Stmt.Fixed.{pattern; _} =
  match pattern with
  | Decl d when d.decl_id <> "pos__" ->
      [(d.decl_id, Type.to_unsized d.decl_type)]
  | SList stmts -> List.concat_map ~f:top_level_decls stmts
  | _ -> []

(** Generate the private data members of the model class *)
let lower_model_private {Program.prepare_data; _} =
  let data_decls = List.concat_map ~f:top_level_decls prepare_data in
  (*Filter out Any data that is not an Eigen matrix*)
  let get_eigen_map (name, ut) =
    if UnsizedType.is_eigen_type ut && not (Transform_Mir.is_opencl_var name)
    then true
    else false in
  let eigen_map_decls = (List.filter ~f:get_eigen_map) data_decls in
  List.map ~f:lower_data_decl data_decls
  @ List.map ~f:lower_map_decl eigen_map_decls

let gen_validate_data name st =
  if String.is_suffix ~suffix:"__" name then []
  else
    let vector args =
      let cast x =
        Exprs.templated_fun_call "static_cast" [Types.size_t] [lower_expr x]
      in
      InitalizerExpr (Types.std_vector Types.size_t, List.map ~f:cast args)
    in
    let open Expression_syntax in
    let context = Var "context__" in
    let validate =
      context.@?(( "validate_dims"
                 , [ literal_string "data initialization"
                   ; literal_string (Mangle.remove_prefix name)
                   ; literal_string
                       (Fmt.to_to_string Cpp.Printing.pp_type_
                          (stantype_prim (SizedType.to_unsized st)) )
                   ; vector (SizedType.get_dims_io st) ] )) in
    [Expression validate]

let gen_assign_data decl_id st =
  let lower_placement_new decl_id st =
    let open Expression_syntax in
    match st with
    | SizedType.SVector (_, d)
     |SRowVector (_, d)
     |SComplexVector d
     |SComplexRowVector d ->
        let data = Var (decl_id ^ "_data__") in
        [ Expression
            (New
               ( Some ("&" ^ decl_id)
               , TypeTrait ("Eigen::Map", [lower_st st DataOnly])
               , [data.@!("data"); lower_expr d] ) ) ]
    | SMatrix (_, d1, d2) | SComplexMatrix (d1, d2) ->
        let data = Var (decl_id ^ "_data__") in
        [ Expression
            (New
               ( Some ("&" ^ decl_id)
               , TypeTrait ("Eigen::Map", [lower_st st DataOnly])
               , [data.@!("data"); lower_expr d1; lower_expr d2] ) ) ]
    | _ -> [] in
  let underlying_var decl_id st =
    match st with
    | SizedType.SVector _ | SRowVector _ | SMatrix _ | SComplexVector _
     |SComplexRowVector _ | SComplexMatrix _ ->
        Var (decl_id ^ "_data__")
    | SInt | SReal | SComplex | SArray _ -> Var decl_id in
  Expression (Assign (underlying_var decl_id st, initialize_value st DataOnly))
  :: lower_placement_new decl_id st

let lower_constructor
    {Program.prog_name; input_vars; prepare_data; output_vars; _} =
  let args =
    [ (Ref (Type_literal "stan::io::var_context"), "context__")
    ; (Type_literal "unsigned int", "random_seed__ = 0")
    ; (Pointer (Type_literal "std::ostream"), "pstream__ = nullptr") ] in
  let preamble =
    [ VarDef
        (make_var_defn ~type_:Int ~name:"current_statement__"
           ~init:(Assignment (Literal "0")) () )
    ; Using ("local_scalar_t__", Some Double)
    ; VarDef
        (make_var_defn ~type_:(Type_literal "boost::ecuyer1988")
           ~name:"base_rng__"
           ~init:
             (Assignment
                (Exprs.fun_call "stan::services::util::create_rng"
                   [Var "random_seed__"; Literal "0"] ) )
           () ) ]
    @ Stmts.unused "base_rng__"
    @ gen_function__ prog_name prog_name
    @ VarDef
        (make_var_defn ~type_:Types.local_scalar ~name:"DUMMY_VAR__"
           ~init:(Construction [Exprs.quiet_NaN])
           () )
      :: Stmts.unused "DUMMY_VAR__" in
  let data_idents = List.map ~f:fst input_vars |> String.Set.of_list in
  let lower_data (Stmt.Fixed.{pattern; meta} as s) =
    match pattern with
    | Decl {decl_id; decl_type; _} when decl_id <> "pos__" -> (
      match decl_type with
      | Sized st -> (
          Locations.create_loc_assignment meta
          @
          match Set.mem data_idents decl_id with
          | true -> gen_validate_data decl_id st @ gen_assign_data decl_id st
          | false -> gen_assign_data decl_id st )
      | Unsized _ -> [] )
    | _ -> lower_statement s in
  let data =
    [Stmts.rethrow_located (List.concat_map ~f:lower_data prepare_data)] in
  let set_num_params =
    let output_params =
      List.filter_map ~f:get_unconstrained_param_st output_vars in
    let add_params par pars =
      List.fold ~init:par ~f:Expression_syntax.( + ) pars in
    match output_params with
    | [] -> Expression (Assign (Var "num_params_r__", Literal "0U"))
    | [par] -> Expression (Assign (Var "num_params_r__", lower_num_param par))
    | par :: pars ->
        Expression
          (Assign
             ( Var "num_params_r__"
             , add_params (lower_num_param par)
                 (List.map ~f:lower_num_param pars) ) ) in
  make_constructor ~args
    ~init_list:[("model_base_crtp", [Literal "0"])]
    ~body:(preamble @ data @ [set_num_params])
    ()

let lower_model_public _ = []

let model_public_basics name =
  [ FunDef
      (make_fun_defn ~inline:true ~return_type:Types.string ~name:"model_name"
         ~cv_qualifiers:[Const; Final]
         ~body:[Return (Some (Exprs.literal_string name))]
         () )
  ; FunDef
      (make_fun_defn ~inline:true
         ~return_type:(Types.std_vector Types.string)
         ~name:"model_compile_info"
         ~body:
           [ Return
               (Some
                  (Exprs.std_vector_expr Types.string
                     [ Exprs.literal_string
                         "stanc_version = %%NAME%%3 %%VERSION%%"
                     ; Exprs.literal_string
                         ("stancflags = " ^ stanc_args_to_print) ] ) ) ]
         () ) ]

let lower_model ({Program.prog_name; _} as p) =
  let private_members = lower_model_private p in
  let public_members = model_public_basics prog_name @ lower_model_public p in
  let constructor = lower_constructor p in
  Class
    (make_class_defn ~name:prog_name ~final:true
       ~base:(Type_literal ("public model_base_crtp<" ^ prog_name ^ ">"))
       ~private_members ~public_members ~constructor () )

(** Create the model's namespace. *)
let namespace Program.{prog_name; _} = prog_name ^ "_namespace"

(** Register functiors used for map_rect.
    Assumes hashtable map_rect_calls is populated *)
let register_map_rect_functors namespace =
  let register_functor (i, f) =
    Preprocessor
      (MacroApply
         ("STAN_REGISTER_MAP_RECT", [string_of_int i; namespace ^ "::" ^ f]) )
  in
  List.map ~f:register_functor
    (List.sort ~compare (Hashtbl.to_alist map_rect_calls))

let usings =
  [ TopUsing ("stan::model::model_base_crtp", None)
  ; TopUsing ("namespace stan::math", None) ]

(** Model boilerplate. *)
let new_model_boilerplate prog_name =
  let new_model =
    let args =
      [ (Ref (Type_literal "stan::io::var_context"), "data_context")
      ; (Type_literal "unsigned int", "seed")
      ; (Pointer (Type_literal "std::ostream"), "msg_stream") ] in
    let body =
      [ VarDef
          (make_var_defn ~type_:(Pointer (Type_literal "stan_model")) ~name:"m"
             ~init:
               (Assignment
                  (New
                     ( None
                     , Type_literal "stan_model"
                     , [Var "data_context"; Var "seed"; Var "msg_stream"] ) ) )
             () ); Return (Some (Literal "*m")) ] in
    FunDef
      (make_fun_defn ~name:"new_model"
         ~return_type:(Ref (Type_literal "stan::model::model_base")) ~args ~body
         () ) in
  let profile_data =
    FunDef
      (make_fun_defn ~name:"get_stan_profile_data"
         ~return_type:(Ref (Type_literal "stan::math::profile_map"))
         ~body:[Return (Some (Literal (prog_name ^ "_namespace::profiles__")))]
         () ) in
  [ TopUsing
      ( "stan_model"
      , Some (Type_literal (prog_name ^ "_namespace::" ^ prog_name)) )
  ; Preprocessor
      (IfNDef ("USING_R", [TopComment "Boilerplate"; new_model; profile_data]))
  ]

let lower_program (p : Program.Typed.t) : Cpp.program =
  Hashtbl.clear Expression_gen.map_rect_calls ;
  (* First, do some transformations on the MIR itself before we begin printing it.*)
  let p, s = Locations.prepare_prog p in
  let model_namespace_str = namespace p in
  let model_contents =
    usings @ Locations.gen_globals s
    @ collect_functors_functions p
    @ if !standalone_functions then [] else [lower_model p] in
  let model_namespace = Namespace (model_namespace_str, model_contents) in
  let global_fns =
    if !standalone_functions then
      List.concat_map
        ~f:(lower_standalone_fun_def model_namespace_str)
        p.functions_block
    else
      new_model_boilerplate p.prog_name
      @ register_map_rect_functors model_namespace_str in
  [version; includes; model_namespace] @ global_fns

module Testing = struct
  open Fmt

  let%expect_test "model public basics" =
    model_public_basics "foobar"
    |> List.hd_exn
    |> str "@[<v>%a" Cpp.Printing.pp_defn
    |> print_endline ;
    [%expect
      {|
      inline std::string model_name() const final
      {
        return "foobar";
      } |}]

  let%expect_test "boilerplate" =
    new_model_boilerplate "foobar"
    |> str "@[<v>%a" (list Cpp.Printing.pp_defn)
    |> print_endline ;
    [%expect
      {|
        using stan_model = foobar_namespace::foobar;
        #ifndef USING_R
        // Boilerplate
        stan::model::model_base&
        new_model(stan::io::var_context& data_context, unsigned int seed,
                  std::ostream* msg_stream)
        {
          stan_model* m = new stan_model(data_context, seed, msg_stream);
          return *m;
        }
        stan::math::profile_map& get_stan_profile_data()
        {
          return foobar_namespace::profiles__;
        }
        #endif |}]
end
